// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID          int32
	Uuid        uuid.UUID
	Username    string
	Email       string
	Password    string
	PhoneNumber sql.NullString
}
